-- # Business questions in postgresql: <br>
select * from customer_shopping_behavior_cleaned;

-- q1. what is the total revenue generated by male vs female ?<br>
SELECT gender, SUM(purchase_amount) AS revenue
from customer_shopping_behavior_cleaned
GROUP BY gender;



-- q2. which customers used a discount vode but still spent more than the average purchase amount?<br>
select customer_id, purchase_amount
from customer_shopping_behavior_cleaned
where discount_applied = 'Yes' and purchase_amount >= 
(select AVG(purchase_amount) from customer_shopping_behavior_cleaned)



-- q3. which are the top 5 products with the highest average review rating?<br>
-- error double precision ROUND won't work, so add ::numeric
select item_purchased, ROUND(avg(review_rating::numeric),2) as "Average Product Rating"
from customer_shopping_behavior_cleaned
group by item_purchased
order by avg(review_rating) DESC
limit 5;


-- q4. compare the average purchase amounts between standard and express shipping<br>
select shipping_type, ROUND(AVG(purchase_amount),2)
from customer_shopping_behavior_cleaned
where shipping_type IN  ('Express', 'Standard')
group by shipping_type;
-- focus on better shipping options 



-- q5. Do subscribe customers spend more? compare average spend and total revenue 
-- between sunscribers and non-subscribed. 
-- spend avarage between subscibers vs non subs.
-- 
SELECT
	subscription_status,
	COUNT(customer_id) as total_customers,
	ROUND(AVG(purchase_amount),2) as avg_spend,
	ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_shopping_behavior_cleaned
group by subscription_status
order by total_revenue, avg_spend desc
-- over 1800 customers are not subscribed , but the avg spend rate
-- is the same. non-subscribed spend a lot MORE!





-- q6. which 5 products have the highest precentage of purchases with discounts applied?
-- which products rely heavily on discounts to sell?
-- percentage ! IMPORTANT QUERY 
select 
item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer_shopping_behavior_cleaned
group by item_purchased
order by discount_rate desc 
limit 5;
-- evertime a product was bought, that percentage number , is the 
-- the times it had a discount.  almost hafl the time for these. 






-- q7. segment customers into 3 categories (new, returning, and loyal) 
-- depending on their total number of previous purchases, and show the 
-- count of each segment.SEGMENTATION IS SUPER IMOORTANT 
-- more than 10 times, is loyal, less than that is not.
-- CTE !
WITH customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment
from customer_shopping_behavior_cleaned
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment 

-- a majority of customers are loyal, and returning and new 
-- are very small




-- q8. what are the top 3 most purchased products within each category?
-- WINDOW FUNCTION! and CTE 
-- 3 types - row_number, dense_rank, and rank.
-- which sell the best? 
WITH item_counts as (
select 
	category, 
	item_purchased,
	count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id) desc) as item_rank
	from customer_shopping_behavior_cleaned
	group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3; 

-- why did we use row_number instead of rank or dense_rank?
--becuase for many items, the numbers are similar, rank and dense_rank
-- will not categorize them like this. here we have the top 3 from ABORT
-- each category , accessories, clothing, footwear etc.
-- here wa have the top 3 of each categoey nicely in a list. 




-- q9. are customers who are repeat buyers (more than 5) also likely to subscribe? <br>
SELECT 
	subscription_status,
	COUNT(customer_id) as repeat_buyers
from customer_shopping_behavior_cleaned
where previous_purchases > 5
group by subscription_status
-- 2500 are subscribed, only 989 are subscribed
-- meaning the subscription is not enticing enough
-- must get better deals for subscriptions. ABORT





-- q10. what is the revenue contrinution of each age group? 
select age_group,
	   sum(purchase_amount) as total_revenue
FROM customer_shopping_behavior_cleaned
group by age_group 
order by total_revenue desc;

-- young adults are the biggest spenders, but 
-- the rest are relatively even. 


